### ISSUE TITLE
Echec de la configuration : Extract data : line 1 colonne 5 (char 4)

### ISSUE THREAD

**Issue by rj2s** [remialban/ipx800v3#1]
Bonjour, j'ai essayé ton intégration IPXV3....
Tout se passe bien pour l'ajout du pont, mais j'ai une erreur une fois démarré : Echec de la configuration : Extract data : line 1 colonne 5 (char 4)
J'ai un ipx800 V3 Firmware version: 3.05.70 Site version: 3.05.70

Merci pour ton support, 
Roland

**Comment by remialban** [comment]
Bonjour Roland,

Merci pour ton message !

J'imagine que ton IPX est sécurisé par un nom d'utilisateur et un mot de passe.
Le problème vient de mon code. En effet, j'ai pris en compte le nom d'utilisateur et le mot de passe pour récupérer l'adresse MAC et la version du firmware de l'IPX mais je n'ai pas pris en compte ces informations-là pour récupérer les autres informations (valeur des capteurs, compteurs et sorties). Du coup HA ne peut pas communiquer avec l'IPX si j'ai pas transmis les info d'authentification. C'est pour cela que tu as une erreur.

Je suis en train de régler le problème et je te tiens au courant dès que possible,
Rémi

**Comment by remialban** [comment]
Je viens normalement de régler le problème. J'ai publié une mise à jour de l'intégration avec les correctifs que j'ai effectués (c'est la dernière version de l'intégration à l'heure où j'ai écris ce message : [1.0.7](https://github.com/remialban/ipx800v3/releases/tag/1.0.7)).

Il faut que tu mettes à jour l'intégration.

Pour que la mise à jour apparaisse instantanément (car souvent HACS met du temps à afficher automatiquement les mises à jour), je te conseille d'aller dans les paramètres de HACS > GCE IPX800 V3 > Cliquer sur les trois petits points > Actualiser les informations.
Ensuite la mise à jour devrait apparaître dans les paramètres d'HA. Il suffira de la faire et de redémarrer HA.

Normalement après cela, tu ne devrais plus avoir d'erreur. Peux-tu faire ces manipulations et me dire si tout fonctionne ?

**Comment by rj2s** [comment]
whaouw....quel support...quelle reactivité...et en + c'est résolu ! bravo, merci.

**Comment by remialban** [comment]
Avec plaisir ! Et merci à toi d'avoir remarqué cette petite erreur !
